// Generated by js_of_ocaml 2.6+git-40b6bc7
(function(aR){"use strict";var
bR=254,aa=255,bo="x",bp="Sys_error",aF=".",bI=224,aK="i",aE="+",ab=65535,bQ="Invalid_argument",bv='"',I=16777215,bH=250,ac=1024,bM="%u",bn="%d",bu="o",bL=110,bm=57343,bl="'",bB=127,bP=512,bt="End_of_file",bs=120,N=" ",br="Failure",bG=-10,aI="e",bg="Undefined_recursive_module",aH="d",bF="% ",bK="X",T="-",bi="Stack_overflow",bA="nan",e="",z=128,bj=240,bk=2048,bz=56320,bE=100,aG=" : file already exists",H="0",by="%+",b=248,bh="Not_found",aJ="%#",S="%",bw="Assert_failure",bx="/",be="5px",bf="toString",bN="Sys_blocked_io",bO="fd ",bd="%i",bJ="Out_of_memory",bD="Match_failure",a="camlinternalFormat.ml",bq="Division_by_zero",bC=1e3;function
av(a,b,c){var
e=new
Array(c);for(var
d=0;d<c;d++)e[d]=a[b+d];return e}function
aQ(a,b,c){var
d=String.fromCharCode;if(b==0&&c<=4096&&c==a.length)return d.apply(null,a);var
f=e;for(;0<c;b+=ac,c-=ac)f+=d.apply(null,av(a,b,Math.min(c,ac)));return f}function
al(a){var
c=new
Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
F(a,b,c,d,e){if(e==0)return 0;if(d==0&&(e>=c.l||c.t==2&&e>=c.c.length)){c.c=a.t==4?aQ(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else
if(c.t==2&&d==c.c.length){c.c+=a.t==4?aQ(a.c,b,e):b==0&&a.c.length==e?a.c:a.c.substr(b,e);c.t=c.c.length==c.l?0:2}else{if(c.t!=4)al(c);var
g=a.c,h=c.c;if(a.t==4)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
ew(a,b){var
e=a.length,d=new
Array(e+1),c=0;for(;c<e;c++)d[c]=a[c];d[c]=b;return d}function
ad(c,b){if(c.fun)return ad(c.fun,b);var
a=c.length,d=b.length,e=a-d;if(e==0)return c.apply(null,b);else
if(e<0)return ad(c.apply(null,av(b,0,a)),av(b,a,d-a));else
return function(a){return ad(c,ew(b,a))}}function
dX(a){if(isFinite(a)){if(Math.abs(a)>=2.22507385850720138e-308)return 0;if(a!=0)return 1;return 2}return isNaN(a)?4:3}function
at(a,b){if(b.repeat)return b.repeat(a);var
c=e,d=0;if(a==0)return c;for(;;){if(a&1)c+=b;a>>=1;if(a==0)return c;b+=b;d++;if(d==9)b.slice(0,1)}}function
am(a){if(a.t==2)a.c+=at(a.l-a.c.length,"\0");else
a.c=aQ(a.c,0,a.c.length);a.t=0}function
bV(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>bB)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
es(a){for(var
k=e,d=e,h,g,i,b,c=0,j=a.length;c<j;c++){g=a.charCodeAt(c);if(g<z){for(var
f=c+1;f<j&&(g=a.charCodeAt(f))<z;f++);if(f-c>bP){d.substr(0,1);k+=d;d=e;k+=a.slice(c,f)}else
d+=a.slice(c,f);if(f==j)break;c=f}b=1;if(++c<j&&((i=a.charCodeAt(c))&-64)==z){h=i+(g<<6);if(g<bI){b=h-12416;if(b<z)b=1}else{b=2;if(++c<j&&((i=a.charCodeAt(c))&-64)==z){h=i+(h<<6);if(g<bj){b=h-925824;if(b<bk||b>=55295&&b<57344)b=2}else{b=3;if(++c<j&&((i=a.charCodeAt(c))&-64)==z&&g<245){b=i-63447168+(h<<6);if(b<65536||b>1114111)b=3}}}}}if(b<4){c-=b;d+="\ufffd"}else
if(b>ab)d+=String.fromCharCode(55232+(b>>10),bz+(b&1023));else
d+=String.fromCharCode(b);if(d.length>ac){d.substr(0,1);k+=d;d=e}}return k+d}function
er(a){switch(a.t){case
9:return a.c;default:am(a);case
0:if(bV(a.c)){a.t=9;return a.c}a.t=8;case
8:return es(a.c)}}function
E(a,b,c){this.t=a;this.c=b;this.l=c}E.prototype.toString=function(){return er(this)};function
ej(a,b){throw[0,a,b]}function
d(a){return new
E(0,a,a.length)}function
b1(a,b){ej(a,d(b))}var
A=[0];function
ae(a){b1(A.Invalid_argument,a)}function
v(a){if(a<0)ae("String.create");return new
E(a?2:9,e,a)}function
dZ(a,b,c,d){if(c>0)if(b==0&&(c>=a.l||a.t==2&&c>=a.c.length))if(d==0){a.c=e;a.t=2}else{a.c=at(c,String.fromCharCode(d));a.t=c==a.l?0:2}else{if(a.t!=4)al(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
aL(a){if((a.t&6)!=0)am(a);return a.c}function
aP(a){a=aL(a);var
e=a.length;if(e>31)ae("format_int: format too long");var
b={justify:aE,signstyle:T,filler:N,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=T;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=H;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;case"d":case"i":b.signedconv=true;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}function
aM(a,b){if(a.uppercase)b=b.toUpperCase();var
g=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!=T))g++;if(a.alternate){if(a.base==8)g+=1;if(a.base==16)g+=2}var
c=e;if(a.justify==aE&&a.filler==N)for(var
f=g;f<a.width;f++)c+=N;if(a.signedconv)if(a.sign<0)c+=T;else
if(a.signstyle!=T)c+=a.signstyle;if(a.alternate&&a.base==8)c+=H;if(a.alternate&&a.base==16)c+="0x";if(a.justify==aE&&a.filler==H)for(var
f=g;f<a.width;f++)c+=H;c+=b;if(a.justify==T)for(var
f=g;f<a.width;f++)c+=N;return d(c)}function
d0(a,b){var
c,f=aP(a),e=f.prec<0?6:f.prec;if(b<0){f.sign=-1;b=-b}if(isNaN(b)){c=bA;f.filler=N}else
if(!isFinite(b)){c="inf";f.filler=N}else
switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)==aI)c=c.slice(0,d-1)+H+c.slice(d-1);break;case"f":c=b.toFixed(e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
i=c.indexOf(aI),h=+c.slice(i+1);if(h<-4||b>=1e+21||b.toFixed(0).length>e){var
d=i-1;while(c.charAt(d)==H)d--;if(c.charAt(d)==aF)d--;c=c.slice(0,d+1)+c.slice(i);d=c.length;if(c.charAt(d-3)==aI)c=c.slice(0,d-1)+H+c.slice(d-1);break}else{var
g=e;if(h<0){g-=h+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)==H)d--;if(c.charAt(d)==aF)d--;c=c.slice(0,d+1)}}break}return aM(f,c)}function
an(a,b){if(aL(a)==bn)return d(e+b);var
c=aP(a);if(b<0)if(c.signedconv){c.sign=-1;b=-b}else
b>>>=0;var
f=b.toString(c.base);if(c.prec>=0){c.filler=N;var
g=c.prec-f.length;if(g>0)f=at(g,H)+f}return aM(c,f)}function
d3(a,b){var
c=a[3]<<16,d=b[3]<<16;if(c>d)return 1;if(c<d)return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
eb(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
em(a,b){a.t&6&&am(a);b.t&6&&am(b);return a.c<b.c?-1:a.c>b.c?1:0}function
bS(a,b,c){var
e=[];for(;;){if(!(c&&a===b))if(a
instanceof
E)if(b
instanceof
E){if(a!==b){var
d=em(a,b);if(d!=0)return d}}else
return 1;else
if(a
instanceof
Array&&a[0]===(a[0]|0)){var
f=a[0];if(f===bR)f=0;if(f===bH){a=a[1];continue}else
if(b
instanceof
Array&&b[0]===(b[0]|0)){var
g=b[0];if(g===bR)g=0;if(g===bH){b=b[1];continue}else
if(f!=g)return f<g?-1:1;else
switch(f){case
248:var
d=eb(a[2],b[2]);if(d!=0)return d;break;case
251:ae("equal: abstract value");case
255:var
d=d3(a,b);if(d!=0)return d;break;default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)e.push(a,b,1)}}else
return 1}else
if(b
instanceof
E||b
instanceof
Array&&b[0]===(b[0]|0))return-1;else
if(typeof
a!="number"&&a&&a.compare)return a.compare(b,c);else{if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!c)return NaN;if(a==a)return 1;if(b==b)return-1}}if(e.length==0)return 0;var
h=e.pop();b=e.pop();a=e.pop();if(h+1<a.length)e.push(a,b,h+1);a=a[h];b=b[h]}}function
d2(a,b){return+(bS(a,b,false)>=0)}function
d6(a){return(a[3]|a[2]|a[1])==0}function
d9(a){return[aa,a&I,a>>24&I,a>>31&ab]}function
bZ(a){var
d=a.length,c=new
Array(d);for(var
b=0;b<d;b++)c[b]=a[b];return c}function
d_(a,b){var
c=a[1]-b[1],d=a[2]-b[2]+(c>>24),e=a[3]-b[3]+(d>>24);return[aa,c&I,d&I,e&ab]}function
bU(a,b){if(a[3]>b[3])return 1;if(a[3]<b[3])return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
bT(a){a[3]=a[3]<<1|a[2]>>23;a[2]=(a[2]<<1|a[1]>>23)&I;a[1]=a[1]<<1&I}function
d7(a){a[1]=(a[1]>>>1|a[2]<<23)&I;a[2]=(a[2]>>>1|a[3]<<23)&I;a[3]=a[3]>>>1}function
ea(a,b){var
e=0,d=bZ(a),c=bZ(b),f=[aa,0,0,0];while(bU(d,c)>0){e++;bT(c)}while(e>=0){e--;bT(f);if(bU(d,c)>=0){f[1]++;d=d_(d,c)}d7(c)}return[0,f,d]}function
d$(a){return a[1]|a[2]<<24}function
d5(a){return a[3]<<16<0}function
d8(a){var
b=-a[1],c=-a[2]+(b>>24),d=-a[3]+(c>>24);return[aa,b&I,c&I,d&ab]}function
d4(a,b){var
c=aP(a);if(c.signedconv&&d5(b)){c.sign=-1;b=d8(b)}var
d=e,i=d9(c.base),h="0123456789abcdef";do{var
g=ea(b,i);b=g[1];d=h.charAt(d$(g[2]))+d}while(!d6(b));if(c.prec>=0){c.filler=N;var
f=c.prec-d.length;if(f>0)d=at(f,H)+d}return aM(c,d)}function
ao(a){return+(a>31&&a<bB)}function
bW(a){return eval(a.toString())}function
ec(a){return av(a,1,a.length-1)}function
ap(a,b,c){return a[b.toString()].apply(a,ec(c))}function
et(a){for(var
g=e,c=g,b,i,d=0,h=a.length;d<h;d++){b=a.charCodeAt(d);if(b<z){for(var
f=d+1;f<h&&(b=a.charCodeAt(f))<z;f++);if(f-d>bP){c.substr(0,1);g+=c;c=e;g+=a.slice(d,f)}else
c+=a.slice(d,f);if(f==h)break;d=f}if(b<bk){c+=String.fromCharCode(192|b>>6);c+=String.fromCharCode(z|b&63)}else
if(b<55296||b>=bm)c+=String.fromCharCode(bI|b>>12,z|b>>6&63,z|b&63);else
if(b>=56319||d+1==h||(i=a.charCodeAt(d+1))<bz||i>bm)c+="\xef\xbf\xbd";else{d++;b=(b<<10)+i-56613888;c+=String.fromCharCode(bj|b>>18,z|b>>12&63,z|b>>6&63,z|b&63)}if(c.length>ac){c.substr(0,1);g+=c;c=e}}return g+c}function
aO(a){var
b=9;if(!bV(a))b=8,a=et(a);return new
E(b,a,a.length)}function
J(a){b1(A.Sys_error,a)}function
ed(a){if(!a.opened)J("Cannot flush a closed channel");if(a.buffer==e)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=e;return 0}var
b3=0;function
ex(){return new
Date().getTime()/bC}function
aS(){return Math.floor(ex())}function
O(a){this.data=a;this.inode=b3++;var
b=aS();this.atime=b;this.mtime=b;this.ctime=b}O.prototype={truncate:function(){this.data=v(0);this.modified()},modified:function(){var
a=aS();this.atime=a;this.mtime=a}};function
g(a){return a.l}function
b0(a){a=a
instanceof
E?a.toString():a;J(a+": No such file or directory")}var
dY=bx;function
aq(a){a=a
instanceof
E?a.toString():a;if(a.charCodeAt(0)!=47)a=dY+a;var
d=a.split(bx),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(e);break;default:b.push(d[c]);break}b.orig=a;return b}function
Q(){this.content={};this.inode=b3++;var
a=aS();this.atime=a;this.mtime=a;this.ctime=a}Q.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
as=new
Q();as.mk(e,new
Q());function
aN(a){var
b=as;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))b0(a.orig);b=b.get(a[c])}return b}function
eq(a){var
c=aq(a),b=aN(c);return b
instanceof
Q?1:0}function
en(a){return new
E(4,a,a.length)}function
eC(a){if(a.t!=4)al(a);return a.c}function
d1(a,b){var
f=aq(a),c=as;for(var
g=0;g<f.length-1;g++){var
e=f[g];if(!c.exists(e))c.mk(e,new
Q());c=c.get(e);if(!(c
instanceof
Q))J(f.orig+aG)}var
e=f[f.length-1];if(c.exists(e))J(f.orig+aG);if(b
instanceof
Q)c.mk(e,b);else
if(b
instanceof
O)c.mk(e,b);else
if(b
instanceof
E)c.mk(e,new
O(b));else
if(b
instanceof
Array)c.mk(e,new
O(en(b)));else
if(b.toString)c.mk(e,new
O(d(b.toString())));else
ae("caml_fs_register");return 0}function
ep(a){var
b=as,d=aq(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
ah(a,b,c){if(A.fds===undefined)A.fds=new
Array();c=c?c:{};var
d={};d.file=b;d.offset=c.append?g(b.data):0;d.flags=c;A.fds[a]=d;A.fd_last_idx=a;return a}function
eD(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
f=a.toString(),h=aq(a);if(d.rdonly&&d.wronly)J(f+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)J(f+" : flags Open_text and Open_binary are not compatible");if(ep(a)){if(eq(a))J(f+" : is a directory");if(d.create&&d.excl)J(f+aG);var
g=A.fd_last_idx?A.fd_last_idx:0,e=aN(h);if(d.truncate)e.truncate();return ah(g+1,e,d)}else
if(d.create){var
g=A.fd_last_idx?A.fd_last_idx:0;d1(a,v(0));var
e=aN(h);return ah(g+1,e,d)}else
b0(a)}ah(0,new
O(v(0)));ah(1,new
O(v(0)));ah(2,new
O(v(0)));function
ee(a){var
b=A.fds[a];if(b.flags.wronly)J(bO+a+" is writeonly");return{file:b.file,offset:b.offset,fd:a,opened:true,refill:null}}function
eu(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=aR.console;b&&b.error&&b.error(a)}function
ev(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=aR.console;b&&b.log&&b.log(a)}var
ar=new
Array();function
el(a,b){var
i=d(b),c=g(i),h=g(a.file.data),f=a.offset;if(f+c>=h){var
e=v(f+c);F(a.file.data,0,e,0,h);F(i,0,e,f,c);a.file.data=e}a.offset+=c;a.file.modified();return 0}function
bX(a){var
b;switch(a){case
1:b=ev;break;case
2:b=eu;break;default:b=el}var
d=A.fds[a];if(d.flags.rdonly)J(bO+a+" is readonly");var
c={file:d.file,offset:d.offset,fd:a,opened:true,buffer:e,output:b};ar[c.fd]=c;return c}function
ef(){var
a=0;for(var
b
in
ar)if(ar[b].opened)a=[0,ar[b],a];return a}if(!Math.imul)Math.imul=function(a,b){b|=0;return((a>>16)*b<<16)+(a&ab)*b|0};var
bY=Math.imul;function
af(a,b){return+(bS(a,b,false)!=0)}function
eh(a){return a
instanceof
Array?a[0]:a
instanceof
E?252:bC}function
c(a,b,c){A[a+1]=b;if(c)A[c]=b}var
eg={};function
ek(a,b){eg[aL(a)]=b;return 0}var
ei=0;function
U(a){a[2]=ei++;return a}function
b2(){ae("index out of bounds")}function
au(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
C(a,b){if(b>>>0>=a.l)b2();return au(a,b)}function
r(a,b,c){c&=aa;if(a.t!=4){if(b==a.c.length){a.c+=String.fromCharCode(c);if(b+1==a.l)a.t=0;return 0}al(a)}a.c[b]=c;return 0}function
ag(a,b,c){if(b>>>0>=a.l)b2();return r(a,b,c)}function
eo(){return 32}function
P(a){var
b=1;while(a&&a.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
k(a,b){return{joo_tramp:a,joo_args:b}}function
j(a,b){return a.length==1?a(b):ad(a,[b])}function
D(a,b,c){return a.length==2?a(b,c):ad(a,[b,c])}var
aU=[b,d(br),-3],aT=[b,d(bQ),-4],s=[b,d(bw),-11];c(11,[b,d(bg),-12],bg);c(10,s,bw);c(9,[b,d(bN),bG],bN);c(8,[b,d(bi),-9],bi);c(7,[b,d(bD),-8],bD);c(6,[b,d(bh),-7],bh);c(5,[b,d(bq),-6],bq);c(4,[b,d(bt),-5],bt);c(3,aT,bQ);c(2,aU,br);c(1,[b,d(bp),-2],bp);c(0,[b,d(bJ),-1],bJ);var
b5=d("true"),b6=d("false"),b4=d("Pervasives.Exit"),b8=d("Array.Bottom"),b$=d("\\b"),ca=d("\\t"),cb=d("\\n"),cc=d("\\r"),b_=d("\\\\"),b9=d("\\'"),cf=d("String.blit / Bytes.blit_string"),ce=d("Bytes.blit"),cd=d("String.sub / Bytes.sub"),cg=d(e),ch=d("Sys.Break"),ci=d("Buffer.add: cannot grow buffer"),cr=d("%c"),cs=d("%s"),ct=d(bd),cu=d("%li"),cv=d("%ni"),cw=d("%Li"),cx=d("%f"),cy=d("%B"),cz=d("%{"),cA=d("%}"),cB=d("%("),cC=d("%)"),cD=d("%a"),cE=d("%t"),cF=d("%?"),cG=d("%r"),cH=d("%_r"),cI=[0,d(a),816,23],cT=[0,d(a),780,21],cL=[0,d(a),781,21],cU=[0,d(a),784,21],cM=[0,d(a),785,21],cV=[0,d(a),788,19],cN=[0,d(a),789,19],cW=[0,d(a),792,22],cO=[0,d(a),793,22],cX=[0,d(a),797,30],cP=[0,d(a),798,30],cR=[0,d(a),802,26],cJ=[0,d(a),803,26],cS=[0,d(a),812,28],cK=[0,d(a),813,28],cQ=[0,d(a),817,23],dy=d(bM),dw=[0,d(a),1449,4],dx=d("Printf: bad conversion %["),dz=[0,d(a),1517,39],dA=[0,d(a),1540,31],dB=[0,d(a),1541,31],a_=d("Printf: bad conversion %_"),dC=d("@{"),dD=d("@["),du=[0,d(bl),[0,d(bl),0]],ds=d(bA),dt=d(aF),dq=d("neg_infinity"),dr=d("infinity"),dp=d("%.12g"),db=[0,d(S),[0,d(aH),0]],dc=[0,d(by),[0,d(aH),0]],dd=[0,d(bF),[0,d(aH),0]],de=[0,d(S),[0,d(aK),0]],df=[0,d(by),[0,d(aK),0]],dg=[0,d(bF),[0,d(aK),0]],dh=[0,d(S),[0,d(bo),0]],di=[0,d(aJ),[0,d(bo),0]],dj=[0,d(S),[0,d(bK),0]],dk=[0,d(aJ),[0,d(bK),0]],dl=[0,d(S),[0,d(bu),0]],dm=[0,d(aJ),[0,d(bu),0]],dn=[0,d(S),[0,d("u"),0]],c0=d(bn),c1=d("%+d"),c2=d("% d"),c3=d(bd),c4=d("%+i"),c5=d("% i"),c6=d("%x"),c7=d("%#x"),c8=d("%X"),c9=d("%#X"),c_=d("%o"),c$=d("%#o"),da=d(bM),cZ=[0,d(bv),[0,d(bv),0]],cj=d("@]"),ck=d("@}"),cl=d("@?"),cm=d("@\n"),cn=d("@."),co=d("@@"),cp=d("@%"),cq=d("@"),cY=d("CamlinternalFormat.Type_mismatch"),dM=d(bf),dL=d(bf),dK=d("Js.Error"),dN=d("preventDefault"),dP=d("createElement"),dQ=d("Dom_html.Canvas_not_available"),dT=[0,[11,d("new_node ("),[4,0,0,0,[11,d(", '"),[2,0,[11,d("');"),0]]]]],d("new_node (%d, '%s');")],dV=d("draw ();");function
q(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,q(a[1])];case
1:return[1,q(a[1])];case
2:return[2,q(a[1])];case
3:return[3,q(a[1])];case
4:return[4,q(a[1])];case
5:return[5,q(a[1])];case
6:return[6,q(a[1])];case
7:return[7,q(a[1])];case
8:var
c=a[1];return[8,c,q(a[2])];case
9:var
b=a[1];return[9,b,b,q(a[3])];case
10:return[10,q(a[1])];case
11:return[11,q(a[1])];case
12:return[12,q(a[1])];case
13:return[13,q(a[1])];default:return[14,q(a[1])]}}function
w(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,w(a[1],b)];case
1:return[1,w(a[1],b)];case
2:return[2,w(a[1],b)];case
3:return[3,w(a[1],b)];case
4:return[4,w(a[1],b)];case
5:return[5,w(a[1],b)];case
6:return[6,w(a[1],b)];case
7:return[7,w(a[1],b)];case
8:var
c=a[1];return[8,c,w(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,w(a[3],b)];case
10:return[10,w(a[1],b)];case
11:return[11,w(a[1],b)];case
12:return[12,w(a[1],b)];case
13:return[13,w(a[1],b)];default:return[14,w(a[1],b)]}}function
p(a,b){if(typeof
a==="number")return b;else
switch(a[0]){case
0:return[0,p(a[1],b)];case
1:return[1,p(a[1],b)];case
2:var
c=a[1];return[2,c,p(a[2],b)];case
3:var
d=a[1];return[3,d,p(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,p(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,p(a[4],b)];case
6:var
k=a[3],l=a[2],m=a[1];return[6,m,l,k,p(a[4],b)];case
7:var
n=a[3],o=a[2],q=a[1];return[7,q,o,n,p(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,p(a[4],b)];case
9:return[9,p(a[1],b)];case
10:return[10,p(a[1],b)];case
11:var
u=a[1];return[11,u,p(a[2],b)];case
12:var
v=a[1];return[12,v,p(a[2],b)];case
13:var
w=a[2],x=a[1];return[13,x,w,p(a[3],b)];case
14:var
y=a[2],z=a[1];return[14,z,y,p(a[3],b)];case
15:return[15,p(a[1],b)];case
16:return[16,p(a[1],b)];case
17:var
A=a[1];return[17,A,p(a[2],b)];case
18:var
B=a[1];return[18,B,p(a[2],b)];case
19:return[19,p(a[1],b)];case
20:var
C=a[2],D=a[1];return[20,D,C,p(a[3],b)];case
21:var
E=a[1];return[21,E,p(a[2],b)];case
22:return[22,p(a[1],b)];case
23:var
F=a[1];return[23,F,p(a[2],b)];default:var
G=a[2],H=a[1];return[24,H,G,p(a[3],b)]}}function
ai(a){throw[0,aT,a]}U([b,b4,0]);function
aj(a){return 0<=a?a:-a|0}function
aV(a,b){var
c=g(a),e=g(b),d=v(c+e|0);F(a,0,d,0,c);F(b,0,d,c,e);return d}ee(0);bX(1);bX(2);U([b,b8,0]);function
aW(a,b){var
c=b;for(;;){if(c){var
d=c[2];j(a,c[1]);var
c=d;continue}return 0}}function
V(a,b){var
c=v(a);dZ(c,0,a,b);return c}function
aX(a,b,c){if(0<=b)if(0<=c)if(!((g(a)-c|0)<b)){var
d=v(c);F(a,b,d,0,c);return d}return ai(cd)}function
aY(a,b,c,d,e){if(0<=e)if(0<=b)if(!((g(a)-e|0)<b))if(0<=d)if(!((g(c)-e|0)<d))return F(a,b,c,d,e);return ai(ce)}function
G(a,b,c,d,e){if(0<=e)if(0<=b)if(!((g(a)-e|0)<b))if(0<=d)if(!((g(c)-e|0)<d))return F(a,b,c,d,e);return ai(cf)}function
aZ(a,b){return V(a,b)}function
aw(d,b){if(b){var
a=b[1],h=[0,0],f=[0,0],i=b[2];aW(function(a){h[1]++;f[1]=f[1]+g(a)|0;return 0},b);var
e=v(f[1]+bY(g(d),h[1]-1|0)|0);F(a,0,e,0,g(a));var
c=[0,g(a)];aW(function(a){F(d,0,e,c[1],g(d));c[1]=c[1]+g(d)|0;F(a,0,e,c[1],g(a));c[1]=c[1]+g(a)|0;return 0},i);return e}return cg}var
a0=eo(0),W=bY(a0/8|0,(1<<(a0+bG|0))-1|0)-1|0;U([b,ch,0]);function
a1(a,b){var
c=[0,a[3]];for(;;){if(c[1]<(a[2]+b|0)){c[1]=2*c[1]|0;continue}if(W<c[1]){if(!((a[2]+b|0)<=W))throw[0,aU,ci];c[1]=W}var
d=v(c[1]);aY(a[1],0,d,0,a[2]);a[1]=d;a[3]=c[1];return 0}}function
X(a,b){var
c=g(b),d=a[2]+c|0;if(a[3]<d)a1(a,c);G(b,0,a[1],a[2],c);a[2]=d;return 0}var
ax=6;function
a2(a){return[0,0,v(a)]}function
a3(a,b){var
c=g(a[2]),d=a[1]+b|0,e=c<d?1:0;if(e){var
f=c*2|0,j=d2(f,d)?f:d,h=v(j);aY(a[2],0,h,0,c);a[2]=h;var
i=0}else
var
i=e;return i}function
Y(a,b){a3(a,1);ag(a[2],a[1],b);a[1]=a[1]+1|0;return 0}function
i(a,b){var
c=g(b);a3(a,c);G(b,0,a[2],a[1],c);a[1]=a[1]+c|0;return 0}function
a4(a){return aX(a[2],0,a[1])}function
ay(a,b){var
c=b;for(;;)if(typeof
c==="number")return 0;else
switch(c[0]){case
0:var
d=c[1];i(a,cr);var
c=d;continue;case
1:var
e=c[1];i(a,cs);var
c=e;continue;case
2:var
f=c[1];i(a,ct);var
c=f;continue;case
3:var
g=c[1];i(a,cu);var
c=g;continue;case
4:var
h=c[1];i(a,cv);var
c=h;continue;case
5:var
j=c[1];i(a,cw);var
c=j;continue;case
6:var
k=c[1];i(a,cx);var
c=k;continue;case
7:var
l=c[1];i(a,cy);var
c=l;continue;case
8:var
m=c[2],n=c[1];i(a,cz);ay(a,n);i(a,cA);var
c=m;continue;case
9:var
o=c[3],p=c[1];i(a,cB);ay(a,p);i(a,cC);var
c=o;continue;case
10:var
q=c[1];i(a,cD);var
c=q;continue;case
11:var
r=c[1];i(a,cE);var
c=r;continue;case
12:var
s=c[1];i(a,cF);var
c=s;continue;case
13:var
t=c[1];i(a,cG);var
c=t;continue;default:var
u=c[1];i(a,cH);var
c=u;continue}}function
t(a){if(typeof
a==="number")return 0;else
switch(a[0]){case
0:return[0,t(a[1])];case
1:return[1,t(a[1])];case
2:return[2,t(a[1])];case
3:return[3,t(a[1])];case
4:return[4,t(a[1])];case
5:return[5,t(a[1])];case
6:return[6,t(a[1])];case
7:return[7,t(a[1])];case
8:var
b=a[1];return[8,b,t(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,t(a[3])];case
10:return[10,t(a[1])];case
11:return[11,t(a[1])];case
12:return[12,t(a[1])];case
13:return[13,t(a[1])];default:return[14,t(a[1])]}}function
n(a){if(typeof
a==="number"){var
v=function(a){return 0},w=function(a){return 0},x=function(a){return 0};return[0,function(a){return 0},x,w,v]}else
switch(a[0]){case
0:var
b=n(a[1]),y=b[4],z=b[3],A=b[2],B=b[1],C=function(a){j(A,0);return 0};return[0,function(a){j(B,0);return 0},C,z,y];case
1:var
c=n(a[1]),D=c[4],E=c[3],F=c[2],G=c[1],H=function(a){j(F,0);return 0};return[0,function(a){j(G,0);return 0},H,E,D];case
2:var
d=n(a[1]),I=d[4],J=d[3],K=d[2],L=d[1],M=function(a){j(K,0);return 0};return[0,function(a){j(L,0);return 0},M,J,I];case
3:var
e=n(a[1]),N=e[4],O=e[3],P=e[2],Q=e[1],R=function(a){j(P,0);return 0};return[0,function(a){j(Q,0);return 0},R,O,N];case
4:var
f=n(a[1]),S=f[4],T=f[3],U=f[2],V=f[1],W=function(a){j(U,0);return 0};return[0,function(a){j(V,0);return 0},W,T,S];case
5:var
g=n(a[1]),X=g[4],Y=g[3],Z=g[2],_=g[1],$=function(a){j(Z,0);return 0};return[0,function(a){j(_,0);return 0},$,Y,X];case
6:var
i=n(a[1]),aa=i[4],ab=i[3],ac=i[2],ad=i[1],ae=function(a){j(ac,0);return 0};return[0,function(a){j(ad,0);return 0},ae,ab,aa];case
7:var
k=n(a[1]),af=k[4],ag=k[3],ah=k[2],ai=k[1],aj=function(a){j(ah,0);return 0};return[0,function(a){j(ai,0);return 0},aj,ag,af];case
8:var
l=n(a[2]),ak=l[4],al=l[3],am=l[2],an=l[1],ao=function(a){j(am,0);return 0};return[0,function(a){j(an,0);return 0},ao,al,ak];case
9:var
ap=a[2],aq=a[1],m=n(a[3]),ar=m[4],as=m[3],at=m[2],au=m[1],o=n(h(t(aq),ap)),av=o[4],aw=o[3],ax=o[2],ay=o[1],az=function(a){j(av,0);j(ar,0);return 0},aA=function(a){j(as,0);j(aw,0);return 0},aB=function(a){j(ax,0);j(at,0);return 0};return[0,function(a){j(au,0);j(ay,0);return 0},aB,aA,az];case
10:var
p=n(a[1]),aC=p[4],aD=p[3],aE=p[2],aF=p[1],aG=function(a){j(aE,0);return 0};return[0,function(a){j(aF,0);return 0},aG,aD,aC];case
11:var
q=n(a[1]),aH=q[4],aI=q[3],aJ=q[2],aK=q[1],aL=function(a){j(aJ,0);return 0};return[0,function(a){j(aK,0);return 0},aL,aI,aH];case
12:var
r=n(a[1]),aM=r[4],aN=r[3],aO=r[2],aP=r[1],aQ=function(a){j(aO,0);return 0};return[0,function(a){j(aP,0);return 0},aQ,aN,aM];case
13:var
s=n(a[1]),aR=s[4],aS=s[3],aT=s[2],aU=s[1],aV=function(a){j(aR,0);return 0},aW=function(a){j(aS,0);return 0},aX=function(a){j(aT,0);return 0};return[0,function(a){j(aU,0);return 0},aX,aW,aV];default:var
u=n(a[1]),aY=u[4],aZ=u[3],a0=u[2],a1=u[1],a2=function(a){j(aY,0);return 0},a3=function(a){j(aZ,0);return 0},a4=function(a){j(a0,0);return 0};return[0,function(a){j(a1,0);return 0},a4,a3,a2]}}function
h(a,b){if(typeof
a==="number")if(typeof
b==="number")return 0;else
switch(b[0]){case
10:var
c=0;break;case
11:var
c=1;break;case
12:var
c=2;break;case
13:var
c=3;break;case
14:var
c=4;break;case
8:var
c=5;break;case
9:var
c=6;break;default:throw[0,s,cI]}else
switch(a[0]){case
0:var
x=a[1];if(typeof
b==="number")var
d=1;else
switch(b[0]){case
0:return[0,h(x,b[1])];case
8:var
c=5,d=0;break;case
9:var
c=6,d=0;break;case
10:var
c=0,d=0;break;case
11:var
c=1,d=0;break;case
12:var
c=2,d=0;break;case
13:var
c=3,d=0;break;case
14:var
c=4,d=0;break;default:var
d=1}if(d)var
c=7;break;case
1:var
y=a[1];if(typeof
b==="number")var
e=1;else
switch(b[0]){case
1:return[1,h(y,b[1])];case
8:var
c=5,e=0;break;case
9:var
c=6,e=0;break;case
10:var
c=0,e=0;break;case
11:var
c=1,e=0;break;case
12:var
c=2,e=0;break;case
13:var
c=3,e=0;break;case
14:var
c=4,e=0;break;default:var
e=1}if(e)var
c=7;break;case
2:var
z=a[1];if(typeof
b==="number")var
f=1;else
switch(b[0]){case
2:return[2,h(z,b[1])];case
8:var
c=5,f=0;break;case
9:var
c=6,f=0;break;case
10:var
c=0,f=0;break;case
11:var
c=1,f=0;break;case
12:var
c=2,f=0;break;case
13:var
c=3,f=0;break;case
14:var
c=4,f=0;break;default:var
f=1}if(f)var
c=7;break;case
3:var
A=a[1];if(typeof
b==="number")var
g=1;else
switch(b[0]){case
3:return[3,h(A,b[1])];case
8:var
c=5,g=0;break;case
9:var
c=6,g=0;break;case
10:var
c=0,g=0;break;case
11:var
c=1,g=0;break;case
12:var
c=2,g=0;break;case
13:var
c=3,g=0;break;case
14:var
c=4,g=0;break;default:var
g=1}if(g)var
c=7;break;case
4:var
B=a[1];if(typeof
b==="number")var
i=1;else
switch(b[0]){case
4:return[4,h(B,b[1])];case
8:var
c=5,i=0;break;case
9:var
c=6,i=0;break;case
10:var
c=0,i=0;break;case
11:var
c=1,i=0;break;case
12:var
c=2,i=0;break;case
13:var
c=3,i=0;break;case
14:var
c=4,i=0;break;default:var
i=1}if(i)var
c=7;break;case
5:var
C=a[1];if(typeof
b==="number")var
k=1;else
switch(b[0]){case
5:return[5,h(C,b[1])];case
8:var
c=5,k=0;break;case
9:var
c=6,k=0;break;case
10:var
c=0,k=0;break;case
11:var
c=1,k=0;break;case
12:var
c=2,k=0;break;case
13:var
c=3,k=0;break;case
14:var
c=4,k=0;break;default:var
k=1}if(k)var
c=7;break;case
6:var
D=a[1];if(typeof
b==="number")var
l=1;else
switch(b[0]){case
6:return[6,h(D,b[1])];case
8:var
c=5,l=0;break;case
9:var
c=6,l=0;break;case
10:var
c=0,l=0;break;case
11:var
c=1,l=0;break;case
12:var
c=2,l=0;break;case
13:var
c=3,l=0;break;case
14:var
c=4,l=0;break;default:var
l=1}if(l)var
c=7;break;case
7:var
E=a[1];if(typeof
b==="number")var
m=1;else
switch(b[0]){case
7:return[7,h(E,b[1])];case
8:var
c=5,m=0;break;case
9:var
c=6,m=0;break;case
10:var
c=0,m=0;break;case
11:var
c=1,m=0;break;case
12:var
c=2,m=0;break;case
13:var
c=3,m=0;break;case
14:var
c=4,m=0;break;default:var
m=1}if(m)var
c=7;break;case
8:var
F=a[2],G=a[1];if(typeof
b==="number")var
p=1;else
switch(b[0]){case
8:var
H=b[1],I=h(F,b[2]);return[8,h(G,H),I];case
10:var
c=0,p=0;break;case
11:var
c=1,p=0;break;case
12:var
c=2,p=0;break;case
13:var
c=3,p=0;break;case
14:var
c=4,p=0;break;default:var
p=1}if(p)throw[0,s,cR];break;case
9:var
J=a[3],K=a[2],L=a[1];if(typeof
b==="number")var
o=1;else
switch(b[0]){case
8:var
c=5,o=0;break;case
9:var
M=b[3],N=b[2],O=b[1],w=n(h(t(K),O)),P=w[4];j(w[2],0);j(P,0);return[9,L,N,h(J,M)];case
10:var
c=0,o=0;break;case
11:var
c=1,o=0;break;case
12:var
c=2,o=0;break;case
13:var
c=3,o=0;break;case
14:var
c=4,o=0;break;default:var
o=1}if(o)throw[0,s,cS];break;case
10:var
Q=a[1];if(typeof
b!=="number"&&10===b[0])return[10,h(Q,b[1])];throw[0,s,cT];case
11:var
R=a[1];if(typeof
b==="number")var
v=1;else
switch(b[0]){case
10:var
c=0,v=0;break;case
11:return[11,h(R,b[1])];default:var
v=1}if(v)throw[0,s,cU];break;case
12:var
S=a[1];if(typeof
b==="number")var
u=1;else
switch(b[0]){case
10:var
c=0,u=0;break;case
11:var
c=1,u=0;break;case
12:return[12,h(S,b[1])];default:var
u=1}if(u)throw[0,s,cV];break;case
13:var
T=a[1];if(typeof
b==="number")var
r=1;else
switch(b[0]){case
10:var
c=0,r=0;break;case
11:var
c=1,r=0;break;case
12:var
c=2,r=0;break;case
13:return[13,h(T,b[1])];default:var
r=1}if(r)throw[0,s,cW];break;default:var
U=a[1];if(typeof
b==="number")var
q=1;else
switch(b[0]){case
10:var
c=0,q=0;break;case
11:var
c=1,q=0;break;case
12:var
c=2,q=0;break;case
13:var
c=3,q=0;break;case
14:return[14,h(U,b[1])];default:var
q=1}if(q)throw[0,s,cX]}switch(c){case
0:throw[0,s,cL];case
1:throw[0,s,cM];case
2:throw[0,s,cN];case
3:throw[0,s,cO];case
4:throw[0,s,cP];case
5:throw[0,s,cJ];case
6:throw[0,s,cK];default:throw[0,s,cQ]}}var
u=U([b,cY,0]);function
az(a,b){if(typeof
a==="number")return[0,0,b];else{if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw u}}function
Z(a,b,c){var
d=az(a,c);if(typeof
b==="number"){if(0===b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw u}return[0,d[1],[0,b[1]],d[2]]}function
dW(a,b,c){if(typeof
b==="number")return[0,0,c];else
switch(b[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
y=o(b[1],c[1]);return[0,[0,y[1]],y[2]]}break;case
1:if(typeof
c!=="number"&&0===c[0]){var
z=o(b[1],c[1]);return[0,[1,z[1]],z[2]]}break;case
2:var
ah=b[2],A=az(b[1],c),g=A[2],ai=A[1];if(typeof
g!=="number"&&1===g[0]){var
B=o(ah,g[1]);return[0,[2,ai,B[1]],B[2]]}throw u;case
3:var
aj=b[2],C=az(b[1],c),h=C[2],ak=C[1];if(typeof
h!=="number"&&1===h[0]){var
D=o(aj,h[1]);return[0,[3,ak,D[1]],D[2]]}throw u;case
4:var
al=b[4],am=b[1],i=Z(b[2],b[3],c),j=i[3],an=i[2],ao=i[1];if(typeof
j!=="number"&&2===j[0]){var
E=o(al,j[1]);return[0,[4,am,ao,an,E[1]],E[2]]}throw u;case
5:var
ap=b[4],aq=b[1],l=Z(b[2],b[3],c),m=l[3],ar=l[2],as=l[1];if(typeof
m!=="number"&&3===m[0]){var
F=o(ap,m[1]);return[0,[5,aq,as,ar,F[1]],F[2]]}throw u;case
6:var
at=b[4],au=b[1],n=Z(b[2],b[3],c),p=n[3],av=n[2],aw=n[1];if(typeof
p!=="number"&&4===p[0]){var
G=o(at,p[1]);return[0,[6,au,aw,av,G[1]],G[2]]}throw u;case
7:var
ax=b[4],ay=b[1],r=Z(b[2],b[3],c),s=r[3],aA=r[2],aB=r[1];if(typeof
s!=="number"&&5===s[0]){var
H=o(ax,s[1]);return[0,[7,ay,aB,aA,H[1]],H[2]]}throw u;case
8:var
aC=b[4],aD=b[1],t=Z(b[2],b[3],c),v=t[3],aE=t[2],aF=t[1];if(typeof
v!=="number"&&6===v[0]){var
I=o(aC,v[1]);return[0,[8,aD,aF,aE,I[1]],I[2]]}throw u;case
9:if(typeof
c!=="number"&&7===c[0]){var
J=o(b[1],c[1]);return[0,[9,J[1]],J[2]]}break;case
10:var
K=o(b[1],c);return[0,[10,K[1]],K[2]];case
11:var
aG=b[1],L=o(b[2],c);return[0,[11,aG,L[1]],L[2]];case
12:var
aH=b[1],M=o(b[2],c);return[0,[12,aH,M[1]],M[2]];case
13:if(typeof
c!=="number"&&8===c[0]){var
N=c[1],aI=c[2],aJ=b[3],aK=b[1];if(af([0,b[2]],[0,N]))throw u;var
O=o(aJ,aI);return[0,[13,aK,N,O[1]],O[2]]}break;case
14:if(typeof
c!=="number"&&9===c[0]){var
P=c[1],aL=c[3],aM=b[3],aN=b[2],aO=b[1],aP=[0,q(P)];if(af([0,q(aN)],aP))throw u;var
Q=o(aM,q(aL));return[0,[14,aO,P,Q[1]],Q[2]]}break;case
15:if(typeof
c!=="number"&&10===c[0]){var
R=o(b[1],c[1]);return[0,[15,R[1]],R[2]]}break;case
16:if(typeof
c!=="number"&&11===c[0]){var
S=o(b[1],c[1]);return[0,[16,S[1]],S[2]]}break;case
17:var
aQ=b[1],T=o(b[2],c);return[0,[17,aQ,T[1]],T[2]];case
18:var
U=b[2],w=b[1];if(0===w[0]){var
Y=w[1],aU=Y[2],_=o(Y[1],c),aV=_[1],$=o(U,_[2]);return[0,[18,[0,[0,aV,aU]],$[1]],$[2]]}var
aa=w[1],aW=aa[2],ab=o(aa[1],c),aX=ab[1],ac=o(U,ab[2]);return[0,[18,[1,[0,aX,aW]],ac[1]],ac[2]];case
19:if(typeof
c!=="number"&&13===c[0]){var
V=o(b[1],c[1]);return[0,[19,V[1]],V[2]]}break;case
20:if(typeof
c!=="number"&&1===c[0]){var
aR=b[2],aS=b[1],W=o(b[3],c[1]);return[0,[20,aS,aR,W[1]],W[2]]}break;case
21:if(typeof
c!=="number"&&2===c[0]){var
aT=b[1],X=o(b[2],c[1]);return[0,[21,aT,X[1]],X[2]]}break;case
23:var
e=b[2],d=b[1];if(typeof
d==="number")switch(d){case
0:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
1:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
2:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
3:if(typeof
c!=="number"&&14===c[0]){var
ad=o(e,c[1]);return[0,[23,3,ad[1]],ad[2]]}throw u;default:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c])}else
switch(d[0]){case
0:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
1:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
2:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
3:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
4:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
5:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
6:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);case
7:return a<50?f(1+a,[7,d[1],d[2]],e,c):k(f,[0,[7,d[1],d[2]],e,c]);case
8:var
aY=d[1],ae=x(d[2],e,c),ag=ae[2];return[0,[23,[8,aY,ae[1]],ag[1]],ag[2]];case
9:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c]);default:return a<50?f(1+a,d,e,c):k(f,[0,d,e,c])}}throw u}function
f(a,b,c,d){var
e=o(c,d);return[0,[23,b,e[1]],e[2]]}function
o(b,c){return P(dW(0,b,c))}function
ey(b,c,d){return P(f(0,b,c,d))}function
x(a,b,c){if(typeof
a==="number")return[0,0,o(b,c)];else
switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
f=x(a[1],b,c[1]);return[0,[0,f[1]],f[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
g=x(a[1],b,c[1]);return[0,[1,g[1]],g[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
i=x(a[1],b,c[1]);return[0,[2,i[1]],i[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
k=x(a[1],b,c[1]);return[0,[3,k[1]],k[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
l=x(a[1],b,c[1]);return[0,[4,l[1]],l[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
m=x(a[1],b,c[1]);return[0,[5,m[1]],m[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
p=x(a[1],b,c[1]);return[0,[6,p[1]],p[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
r=x(a[1],b,c[1]);return[0,[7,r[1]],r[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
s=c[1],D=c[2],E=a[2];if(af([0,a[1]],[0,s]))throw u;var
v=x(E,b,D);return[0,[8,s,v[1]],v[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],e=c[1],F=c[3],G=a[3],H=a[2],I=a[1],J=[0,q(e)];if(af([0,q(I)],J))throw u;var
K=[0,q(d)];if(af([0,q(H)],K))throw u;var
w=n(h(t(e),d)),L=w[4];j(w[2],0);j(L,0);var
y=x(q(G),b,F),M=y[2];return[0,[9,e,d,t(y[1])],M]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
z=x(a[1],b,c[1]);return[0,[10,z[1]],z[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
A=x(a[1],b,c[1]);return[0,[11,A[1]],A[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
B=x(a[1],b,c[1]);return[0,[13,B[1]],B[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
C=x(a[1],b,c[1]);return[0,[14,C[1]],C[2]]}break}throw u}function
y(a,b,c){var
d=g(c),l=0<=b?a:0,f=aj(b);if(f<=d)return c;var
m=2===l?48:32,e=V(f,m);switch(l){case
0:G(c,0,e,0,d);break;case
1:G(c,0,e,f-d|0,d);break;default:if(0<d){if(43===C(c,0))var
h=1;else
if(45===C(c,0))var
h=1;else
if(32===C(c,0))var
h=1;else
var
j=0,h=0;if(h){ag(e,0,C(c,0));G(c,1,e,(f-d|0)+1|0,d-1|0);var
j=1}}else
var
j=0;if(!j){if(1<d)if(48===C(c,0)){if(bs===C(c,1))var
k=1;else
if(88===C(c,1))var
k=1;else
var
i=0,k=0;if(k){ag(e,1,C(c,1));G(c,2,e,(f-d|0)+2|0,d-2|0);var
i=1}}else
var
i=0;else
var
i=0;if(!i)G(c,0,e,f-d|0,d)}}return e}function
R(a,b){var
d=aj(a),c=g(b),e=C(b,0);if(58<=e)var
f=71<=e?5<(e-97|0)>>>0?1:0:65<=e?0:1;else{if(32===e)var
h=1;else
if(43<=e)switch(e-43|0){case
5:if(c<(d+2|0))if(1<c){var
l=bs===C(b,1)?0:88===C(b,1)?0:1;if(!l){var
j=V(d+2|0,48);ag(j,1,C(b,1));G(b,2,j,(d-c|0)+4|0,c-2|0);return j}}var
f=0,h=0;break;case
0:case
2:var
h=1;break;case
1:case
3:case
4:var
f=1,h=0;break;default:var
f=0,h=0}else
var
f=1,h=0;if(h){if(c<(d+1|0)){var
i=V(d+1|0,48);ag(i,0,e);G(b,1,i,(d-c|0)+2|0,c-1|0);return i}var
f=1}}if(!f)if(c<d){var
k=V(d,48);G(b,0,k,d-c|0,c);return k}return b}function
a5(a){var
l=0;for(;;){if(g(a)<=l)var
n=0;else{var
f=au(a,l),A=14<=f?34===f?1:92===f?1:0:11<=f?13<=f?1:0:8<=f?1:0;if(A)var
n=1;else{if(ao(f)){var
l=l+1|0;continue}var
n=1}}if(n){var
b=[0,0],s=g(a)-1|0,u=0;if(!(s<0)){var
k=u;for(;;){var
e=au(a,k),B=14<=e?34===e?1:92===e?1:0:11<=e?13<=e?1:0:8<=e?1:0,y=B?2:ao(e)?1:4;b[1]=b[1]+y|0;var
z=k+1|0;if(s!==k){var
k=z;continue}break}}if(b[1]===g(a)){var
p=g(a),q=v(p);F(a,0,q,0,p);var
o=q}else{var
c=v(b[1]);b[1]=0;var
t=g(a)-1|0,w=0;if(!(t<0)){var
i=w;for(;;){var
d=au(a,i),j=d-34|0;if(58<j>>>0)if(-20<=j)var
m=1;else{switch(j+34|0){case
8:r(c,b[1],92);b[1]++;r(c,b[1],98);var
h=1;break;case
9:r(c,b[1],92);b[1]++;r(c,b[1],116);var
h=1;break;case
10:r(c,b[1],92);b[1]++;r(c,b[1],bL);var
h=1;break;case
13:r(c,b[1],92);b[1]++;r(c,b[1],114);var
h=1;break;default:var
m=1,h=0}if(h)var
m=0}else
var
m=56<(j-1|0)>>>0?(r(c,b[1],92),b[1]++,r(c,b[1],d),0):1;if(m)if(ao(d))r(c,b[1],d);else{r(c,b[1],92);b[1]++;r(c,b[1],48+(d/bE|0)|0);b[1]++;r(c,b[1],48+((d/10|0)%10|0)|0);b[1]++;r(c,b[1],48+(d%10|0)|0)}b[1]++;var
x=i+1|0;if(t!==i){var
i=x;continue}break}}var
o=c}}else
var
o=a;return aw(o,cZ)}}function
aA(a,b){switch(a){case
0:var
c=db;break;case
1:var
c=dc;break;case
2:var
c=dd;break;case
3:var
c=de;break;case
4:var
c=df;break;case
5:var
c=dg;break;case
6:var
c=dh;break;case
7:var
c=di;break;case
8:var
c=dj;break;case
9:var
c=dk;break;case
10:var
c=dl;break;case
11:var
c=dm;break;default:var
c=dn}return aw(aZ(1,b),c)}function
a6(a,b){switch(a){case
0:var
c=c0;break;case
1:var
c=c1;break;case
2:var
c=c2;break;case
3:var
c=c3;break;case
4:var
c=c4;break;case
5:var
c=c5;break;case
6:var
c=c6;break;case
7:var
c=c7;break;case
8:var
c=c8;break;case
9:var
c=c9;break;case
10:var
c=c_;break;case
11:var
c=c$;break;default:var
c=da}return an(c,b)}function
a7(a,b){return an(aA(a,108),b)}function
a8(a,b){return an(aA(a,bL),b)}function
a9(a,b){return d4(aA(a,76),b)}function
K(a,b,c){var
q=aj(b);if(15===a)var
m=dp;else{var
p=aj(q);switch(a){case
15:var
h=70;break;case
0:case
1:case
2:var
h=102;break;case
3:case
4:case
5:var
h=101;break;case
6:case
7:case
8:var
h=69;break;case
9:case
10:case
11:var
h=103;break;default:var
h=71}var
f=a2(16);Y(f,37);switch(a){case
1:case
4:case
7:case
10:case
13:Y(f,43);break;case
2:case
5:case
8:case
11:case
14:Y(f,32);break}Y(f,46);i(f,d(e+p));Y(f,h);var
m=a4(f)}var
j=d0(m,c);if(15===a){var
n=dX(c),r=g(j);if(3===n)return c<0?dq:dr;if(4<=n)return ds;var
k=0;for(;;){if(k===r)var
o=0;else{var
l=C(j,k)-46|0,s=23<l>>>0?55===l?1:0:21<(l-1|0)>>>0?1:0;if(!s){var
k=k+1|0;continue}var
o=1}return o?j:aV(j,dt)}}return j}function
$(a,b,i,d,e){var
h=b,f=d,g=e;for(;;)if(typeof
g==="number")return D(h,i,f);else
switch(g[0]){case
0:var
Q=g[1];return function(a){return l(h,i,[5,f,a],Q)};case
1:var
R=g[1];return function(a){if(39===a)var
b=b9;else
if(92===a)var
b=b_;else{if(14<=a)var
c=0;else
switch(a){case
8:var
b=b$,c=1;break;case
9:var
b=ca,c=1;break;case
10:var
b=cb,c=1;break;case
13:var
b=cc,c=1;break;default:var
c=0}if(!c)if(ao(a)){var
e=v(1);r(e,0,a);var
b=e}else{var
d=v(4);r(d,0,92);r(d,1,48+(a/bE|0)|0);r(d,2,48+((a/10|0)%10|0)|0);r(d,3,48+(a%10|0)|0);var
b=d}}return l(h,i,[4,f,aw(b,du)],R)};case
2:var
J=g[2],M=g[1];return a<50?_(1+a,h,i,f,J,M,function(a){return a}):k(_,[0,h,i,f,J,M,function(a){return a}]);case
3:return a<50?_(1+a,h,i,f,g[2],g[1],a5):k(_,[0,h,i,f,g[2],g[1],a5]);case
4:return a<50?L(1+a,h,i,f,g[4],g[2],g[3],a6,g[1]):k(L,[0,h,i,f,g[4],g[2],g[3],a6,g[1]]);case
5:return a<50?L(1+a,h,i,f,g[4],g[2],g[3],a7,g[1]):k(L,[0,h,i,f,g[4],g[2],g[3],a7,g[1]]);case
6:return a<50?L(1+a,h,i,f,g[4],g[2],g[3],a8,g[1]):k(L,[0,h,i,f,g[4],g[2],g[3],a8,g[1]]);case
7:return a<50?L(1+a,h,i,f,g[4],g[2],g[3],a9,g[1]):k(L,[0,h,i,f,g[4],g[2],g[3],a9,g[1]]);case
8:var
w=g[4],x=g[3],A=g[2],z=g[1];if(typeof
A==="number"){if(typeof
x==="number")return 0===x?function(a){return l(h,i,[4,f,K(z,ax,a)],w)}:function(a,b){return l(h,i,[4,f,K(z,a,b)],w)};var
ag=x[1];return function(a){return l(h,i,[4,f,K(z,ag,a)],w)}}else{if(0===A[0]){var
F=A[2],G=A[1];if(typeof
x==="number")return 0===x?function(a){return l(h,i,[4,f,y(G,F,K(z,ax,a))],w)}:function(a,b){return l(h,i,[4,f,y(G,F,K(z,a,b))],w)};var
ah=x[1];return function(a){return l(h,i,[4,f,y(G,F,K(z,ah,a))],w)}}var
H=A[1];if(typeof
x==="number")return 0===x?function(a,b){return l(h,i,[4,f,y(H,a,K(z,ax,b))],w)}:function(a,b,c){return l(h,i,[4,f,y(H,a,K(z,b,c))],w)};var
ai=x[1];return function(a,b){return l(h,i,[4,f,y(H,a,K(z,ai,b))],w)}}case
9:var
S=g[1];return function(a){var
b=a?b5:b6;return l(h,i,[4,f,b],S)};case
10:var
f=[7,f],g=g[1];continue;case
11:var
f=[2,f,g[1]],g=g[2];continue;case
12:var
f=[3,f,g[1]],g=g[2];continue;case
13:var
T=g[3],U=g[2],I=a2(16);ay(I,U);var
P=a4(I);return function(a){return l(h,i,[4,f,P],T)};case
14:var
V=g[3],W=g[2];return function(a){var
c=a[1],b=o(c,q(t(W)));if(typeof
b[2]==="number")return l(h,i,f,p(b[1],V));throw u};case
15:var
X=g[1];return function(c,b){return l(h,i,[6,f,function(a){return D(c,a,b)}],X)};case
16:var
Y=g[1];return function(a){return l(h,i,[6,f,a],Y)};case
17:var
f=[0,f,g[1]],g=g[2];continue;case
18:var
C=g[1];if(0===C[0]){var
c=g[2],Z=C[1][1],$=0,h=function(f,h,c){return function(a,b){return l(h,a,[1,f,[0,b]],c)}}(f,h,c),f=$,g=Z;continue}var
E=g[2],aa=C[1][1],ab=0,h=function(f,h,E){return function(a,b){return l(h,a,[1,f,[1,b]],E)}}(f,h,E),f=ab,g=aa;continue;case
19:throw[0,s,dw];case
20:var
ac=g[3],ad=[8,f,dx];return function(a){return l(h,i,ad,ac)};case
21:var
ae=g[2];return function(a){return l(h,i,[4,f,an(dy,a)],ae)};case
22:var
af=g[1];return function(a){return l(h,i,[5,f,a],af)};case
23:var
n=g[2],B=g[1];if(typeof
B==="number")switch(B){case
0:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
1:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
2:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
3:throw[0,s,dz];default:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n])}else
switch(B[0]){case
0:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
1:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
2:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
3:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
4:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
5:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
6:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
7:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);case
8:return a<50?aD(1+a,h,i,f,B[2],n):k(aD,[0,h,i,f,B[2],n]);case
9:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n]);default:return a<50?m(1+a,h,i,f,n):k(m,[0,h,i,f,n])}default:var
N=g[3],O=g[1];return a<50?aC(1+a,h,i,f,N,O,j(g[2],0)):k(aC,[0,h,i,f,N,O,j(g[2],0)])}}function
aD(a,g,c,d,e,f){if(typeof
e==="number")return a<50?m(1+a,g,c,d,f):k(m,[0,g,c,d,f]);else
switch(e[0]){case
0:var
b=e[1];return function(a){return B(g,c,d,b,f)};case
1:var
i=e[1];return function(a){return B(g,c,d,i,f)};case
2:var
j=e[1];return function(a){return B(g,c,d,j,f)};case
3:var
l=e[1];return function(a){return B(g,c,d,l,f)};case
4:var
n=e[1];return function(a){return B(g,c,d,n,f)};case
5:var
o=e[1];return function(a){return B(g,c,d,o,f)};case
6:var
p=e[1];return function(a){return B(g,c,d,p,f)};case
7:var
q=e[1];return function(a){return B(g,c,d,q,f)};case
8:var
r=e[2];return function(a){return B(g,c,d,r,f)};case
9:var
u=e[3],v=e[2],x=h(t(e[1]),v);return function(a){return B(g,c,d,w(x,u),f)};case
10:var
y=e[1];return function(a,b){return B(g,c,d,y,f)};case
11:var
z=e[1];return function(a){return B(g,c,d,z,f)};case
12:var
A=e[1];return function(a){return B(g,c,d,A,f)};case
13:throw[0,s,dA];default:throw[0,s,dB]}}function
m(a,b,c,d,e){return a<50?$(1+a,b,c,[8,d,a_],e):k($,[0,b,c,[8,d,a_],e])}function
_(a,h,c,d,e,f,g){if(typeof
f==="number")return function(a){return l(h,c,[4,d,j(g,a)],e)};else{if(0===f[0]){var
b=f[2],i=f[1];return function(a){return l(h,c,[4,d,y(i,b,j(g,a))],e)}}var
k=f[1];return function(a,b){return l(h,c,[4,d,y(k,a,j(g,b))],e)}}}function
L(a,k,j,d,e,f,g,h,i){if(typeof
f==="number"){if(typeof
g==="number")return 0===g?function(a){return l(k,j,[4,d,D(h,i,a)],e)}:function(a,b){return l(k,j,[4,d,R(a,D(h,i,b))],e)};var
b=g[1];return function(a){return l(k,j,[4,d,R(b,D(h,i,a))],e)}}else{if(0===f[0]){var
c=f[2],m=f[1];if(typeof
g==="number")return 0===g?function(a){return l(k,j,[4,d,y(m,c,D(h,i,a))],e)}:function(a,b){return l(k,j,[4,d,y(m,c,R(a,D(h,i,b)))],e)};var
o=g[1];return function(a){return l(k,j,[4,d,y(m,c,R(o,D(h,i,a)))],e)}}var
n=f[1];if(typeof
g==="number")return 0===g?function(a,b){return l(k,j,[4,d,y(n,a,D(h,i,b))],e)}:function(a,b,c){return l(k,j,[4,d,y(n,a,R(b,D(h,i,c)))],e)};var
p=g[1];return function(a,b){return l(k,j,[4,d,y(n,a,R(p,D(h,i,b)))],e)}}}function
aC(a,b,c,d,e,f,g){if(f){var
h=f[1];return function(a){return dv(b,c,d,e,h,j(g,a))}}return a<50?$(1+a,b,c,[4,d,g],e):k($,[0,b,c,[4,d,g],e])}function
l(b,i,d,e){return P($(0,b,i,d,e))}function
B(g,c,d,e,f){return P(aD(0,g,c,d,e,f))}function
ez(b,c,d,e){return P(m(0,b,c,d,e))}function
eA(h,c,d,e,f,g){return P(_(0,h,c,d,e,f,g))}function
eB(k,j,d,e,f,g,h,i){return P(L(0,k,j,d,e,f,g,h,i))}function
dv(b,c,d,e,f,g){return P(aC(0,b,c,d,e,f,g))}function
M(a,b){var
c=b;for(;;)if(typeof
c==="number")return 0;else
switch(c[0]){case
0:var
e=c[2],i=c[1];if(typeof
e==="number")switch(e){case
0:var
d=cj;break;case
1:var
d=ck;break;case
2:var
d=cl;break;case
3:var
d=cm;break;case
4:var
d=cn;break;case
5:var
d=co;break;default:var
d=cp}else
switch(e[0]){case
0:var
d=e[1];break;case
1:var
d=e[1];break;default:var
d=aV(cq,aZ(1,e[1]))}M(a,i);return X(a,d);case
1:var
g=c[2],h=c[1];if(0===g[0]){var
k=g[1];M(a,h);X(a,dC);var
c=k;continue}var
l=g[1];M(a,h);X(a,dD);var
c=l;continue;case
6:var
o=c[2];M(a,c[1]);return X(a,j(o,0));case
7:var
c=c[1];continue;case
8:var
p=c[2];M(a,c[1]);return ai(p);case
2:case
4:var
m=c[2];M(a,c[1]);return X(a,m);default:var
n=c[2];M(a,c[1]);var
f=a[2];if(a[3]<=f)a1(a,1);r(a[1],f,n);a[2]=f+1|0;return 0}}var
a$=[0,0];function
dE(a){var
b=a[1];return l(function(a,b){var
g=64,d=1<=64?g:1,e=W<d?W:d,f=v(e),c=[0,f,0,e,f];M(c,b);return aX(c[1],0,c[2])},0,0,b)}function
ba(a){a$[1]=[0,a,a$[1]];return 0}var
ak=aR,dJ=ak.Array,bb=U([b,dK,0]),aB=[0,bb,{}],dG=null,dH=undefined,dI=false,dF=eh(aB)===b?aB:aB[1];ek(d("jsError"),dF);ba(function(a){return a[1]===bb?[0,aO(ap(a[2],dL,[0]))]:0});ba(function(a){return a
instanceof
dJ?0:[0,aO(ap(a,dM,[0]))]});var
dO=ak.document;U([b,dQ,0]);ak.HTMLElement===dH;function
dR(a){return aO(a.outerHTML)}function
dS(a,b){var
c=dR(b);return bW(D(dE(dT),a,c))}function
dU(a){return bW(dV)}function
bc(a){dU(0);var
b=ap(dO,dP,[0,"span"]);b.innerHTML="Foo";b.style.fontSize="3em";b.style.padding=be;b.style.borderColor="#FF00FF";b.style.borderWidth=be;b.style.borderStyle="solid";dS(3,b);return dI}ak.onload=function(a){if(1-(a==dG?1:0)){var
c=bc(a);if(!(c|0))ap(a,dN,[0]);return c}var
d=event,b=bc(d);if(!(b|0))d.returnValue=b;return b};function
b7(a){var
b=a;for(;;){if(b){var
c=b[2],d=b[1];try{ed(d)}catch(f){}var
b=c;continue}return 0}}b7(ef(0));return}(function(){return this}()));
